### PR TITLE
feat(ssl): added basic ssl implementation

### PR DESCRIPTION
**Pull request by martinopresnik**

### CODE REVIEW

**Comment by irmana** [comment]
@martinopresnik is this work in progress or you think it's ready for the review?

**Comment by martinopresnik** [comment]
@irmana This is work in progress.

**Comment by martinopresnik** [comment]
@irmana PR is ready for review, but currently without tests.

**Review by jkuri — APPROVED** [review]
this is more than a solid PR from your side @martinopresnik 🥇 💯

**Pull request merged**
